### ISSUE TITLE
За счет чего резюме повышается в списках?

### ISSUE THREAD

**Issue by KurKuza** [sergo-code/hh-ru-auto-resume-raising#4]
Не понял, что бот делает, чтобы повысить резюме в списках
Можно пожалуйста чуть больше описания? :)

**Comment by sergo-code** [comment]
Добрый день!
За поднятие резюме отвечает функция raise_resume() (services/main.py). 
Необходимый минимум для выполнения данной задачи:
1) Войти в профиль.
2) Отправить действие(поднятие резюме) на сервер.
```
import asyncio
import os

from dotenv import load_dotenv
from services.main import HHru

load_dotenv()


async def main():
    hh = HHru(os.getenv('phone'), os.getenv('password'), None)
    await hh.login()
    await hh.raise_resume('id вашего резюме')


asyncio.run(main())
```
