### ISSUE TITLE
time.tzset()

### ISSUE THREAD

**Issue by Genolium** [sergo-code/hh-ru-auto-resume-raising#5]
time.tzset() не поддерживается вашей ос windows

**Comment by sergo-code** [comment]
Добрый день!
Функция time.tzset() не поддерживается ОС Windows, для этой задачи можно использовать Linux системы.

**Comment by Genolium** [comment]
Добрый день, я знаю, и что делать пользователям Windows?

**Comment by RootShell-coder** [comment]
У пользователей windows есть WSL

**Comment by Genolium** [comment]
> У пользователей windows есть WSL

Великолепный фикс того, что прога не работает на Windows

**Comment by Genolium** [comment]
<img width="296" alt="image" src="https://github.com/sergo-code/hh-ru-auto-resume-raising/assets/82310948/3de3ea19-6185-46c7-9b1f-3a04fa310df7">
клоунада
